<a href="https://colab.research.google.com/github/CodesbyHim/Numpy/blob/main/Numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
b = np.zeros((3,4))

In [6]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b.ndim

2

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.two(5) #doesn't exists in numpy

AttributeError: module 'numpy' has no attribute 'two'

In [64]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [65]:
arr = np.zeros((3,4))

In [66]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
arr.ndim

2

In [68]:
#3 dimensional array

In [10]:
np.zeros(1)

array([0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.zeros((3,4))
arr.ndim

2

In [13]:
arr = np.zeros((1,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
# 4 dimensional array
arr = np.zeros((1,1,3,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [15]:
arr.ndim

4

In [16]:
# 5 dimensional array
arr = np.zeros((1,1,1,3,4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [17]:
arr.ndim

5

In [18]:
arr = np.zeros((3,4))

In [19]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr.shape

(3, 4)

In [21]:
arr.size

12

In [22]:
arr.ndim

2

In [23]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr -5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [26]:
arr * 5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr1 = np.ones((3,4))

In [28]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr1 - 4

array([[-3., -3., -3., -3.],
       [-3., -3., -3., -3.],
       [-3., -3., -3., -3.]])

In [30]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [32]:
# useful in calculating the inverse of matrix

In [33]:
np.empty((3,4)) #Return a new array of given shape and type, without initializing entries.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [34]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.empty((3,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [36]:
# Optional
# This random module helps us to generate a random number.

import random
random.choice((1,2,3,4,5))

3

In [37]:
random.choice('Himanshu')

'a'

In [38]:
random.randrange(1,100)

5

In [39]:
random.random() # a random no. is generated between o(included) and 1(excluded)

0.037769115828694244

In [40]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [41]:
random.shuffle(lis)

In [42]:
lis

[4, 2, 3, 1, 5]

In [43]:
random.uniform(7,14)

11.451572839846747

In [44]:
# to have random no.s related concepts in numpy
np.array([])

array([], dtype=float64)

In [45]:
np.random.random_sample()

0.49075976764722684

In [46]:
np.random.random_sample((5, ))

array([0.83115584, 0.69120982, 0.04316899, 0.1605445 , 0.40789928])

In [47]:
np.random.rand(1)

array([0.97074337])

In [48]:
np.random.rand(2,3)

array([[0.51353877, 0.58614681, 0.69922724],
       [0.61463668, 0.10187863, 0.9609998 ]])

In [49]:
aw = np.random.random_sample((3,4 ))

In [50]:
aw

array([[0.94225889, 0.27925562, 0.54017756, 0.0111054 ],
       [0.76500026, 0.17820264, 0.41313089, 0.21416826],
       [0.61445752, 0.13437591, 0.92861704, 0.65311015]])

In [51]:
aw.ndim

2

In [52]:
np.random.randn(2,3)

array([[ 0.54193518, -0.7667203 ,  1.54614408],
       [-1.27510939, -0.50148923,  1.78768813]])

In [53]:
arr = np.random.randint(1,4, size = (3,4))

In [54]:
arr.ndim

2

In [55]:
arr.shape

(3, 4)

In [56]:
arr.size

12

In [57]:
arr

array([[1, 2, 2, 1],
       [2, 3, 2, 3],
       [1, 1, 2, 2]])

In [58]:
# reshaping the array
arr1 = arr.reshape(2,6)

In [59]:
arr1.shape

(2, 6)

In [60]:
arr1.size

12

In [61]:
#array size will not change,always reshape parameter
# should be multiplication of original array size.

In [62]:
arr.reshape(1,12)

array([[1, 2, 2, 1, 2, 3, 2, 3, 1, 1, 2, 2]])

In [63]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [69]:
arr.reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# Case when you don't know in reshape what should be the column count
arr.reshape(4, -1)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
arr.reshape(2,-1)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [72]:
arr.reshape(2,-100)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [73]:
# you know column count but no row count
arr1 = arr.reshape(-1, 3)

In [74]:
arr1.size

12

In [75]:
arr.reshape(12,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [76]:
arr.reshape(12,1).base # to see the original array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
arr.reshape(2,2,3)

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [80]:
arr.reshape(1,2,2,3)

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [81]:
arr.reshape(4,3,1) #3 rows 1 column repeated 4 times in the third dimension.

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [82]:
# Conditions on array

arr1 = np.random.randint(1,10,(5,6))

In [83]:
arr1

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7],
       [2, 9, 5, 1, 5, 9],
       [3, 4, 4, 5, 5, 4],
       [5, 9, 8, 7, 8, 6]])

In [84]:
arr1.shape

(5, 6)

In [85]:
arr1.ndim

2

In [86]:
arr1.size

30

In [87]:
arr1 > 3

array([[ True, False, False,  True, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [88]:
arr1[arr1>3]

array([8, 9, 6, 6, 9, 7, 7, 9, 7, 9, 5, 5, 9, 4, 4, 5, 5, 4, 5, 9, 8, 7,
       8, 6])

In [89]:
arr1[arr1<3]

array([2, 2, 2, 1])

In [90]:
arr1

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7],
       [2, 9, 5, 1, 5, 9],
       [3, 4, 4, 5, 5, 4],
       [5, 9, 8, 7, 8, 6]])

In [91]:
# Accessing elements in the array.
arr1[0]

array([8, 3, 2, 9, 2, 6])

In [92]:
arr1[1]

array([6, 9, 7, 7, 9, 7])

In [93]:
arr1[1][0]

6

In [94]:
arr1

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7],
       [2, 9, 5, 1, 5, 9],
       [3, 4, 4, 5, 5, 4],
       [5, 9, 8, 7, 8, 6]])

In [95]:
arr1[0:2]

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7]])

In [96]:
arr1[0:3] #zeroth row, 1st row and 2nd row

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7],
       [2, 9, 5, 1, 5, 9]])

In [97]:
arr1[0:3,[0,2]] #0 to 2nd row and 0th and 2nd column

array([[8, 2],
       [6, 7],
       [2, 5]])

In [98]:
# Slicing on both rows and column

In [99]:
arr1

array([[8, 3, 2, 9, 2, 6],
       [6, 9, 7, 7, 9, 7],
       [2, 9, 5, 1, 5, 9],
       [3, 4, 4, 5, 5, 4],
       [5, 9, 8, 7, 8, 6]])

In [100]:
arr1[0:3, 1:3]

array([[3, 2],
       [9, 7],
       [9, 5]])

In [101]:
arr1[0:2,[0,1]]

array([[8, 3],
       [6, 9]])

In [102]:
arr1[0,[1,3]]

array([3, 9])

In [103]:
arr1[2:4,[0,3]]

array([[2, 1],
       [3, 5]])

In [104]:
arr1[2:5]

array([[2, 9, 5, 1, 5, 9],
       [3, 4, 4, 5, 5, 4],
       [5, 9, 8, 7, 8, 6]])

In [105]:
arr1[2:5,0:2]

array([[2, 9],
       [3, 4],
       [5, 9]])

In [106]:
# Mathematical calculations on array

arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [107]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [108]:
arr2

array([[2, 2, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [109]:
arr1 + arr2 # indexwise addition of arrays

array([[4, 3, 2],
       [3, 3, 3],
       [2, 4, 2]])

In [110]:
arr1 - arr2 # indexwise subtraction

array([[ 0, -1,  0],
       [ 1, -1, -1],
       [ 0,  0,  0]])

In [111]:
arr1 * arr2 # indexwise multiplication

array([[4, 2, 1],
       [2, 2, 2],
       [1, 4, 1]])

In [112]:
arr1,arr2

(array([[2, 1, 1],
        [2, 1, 1],
        [1, 2, 1]]),
 array([[2, 2, 1],
        [1, 2, 2],
        [1, 2, 1]]))

In [113]:
arr1 / arr2 #indexwise division

array([[1. , 0.5, 1. ],
       [2. , 0.5, 0.5],
       [1. , 1. , 1. ]])

In [114]:
# matrix multiplication >>> different from index wise multiplication

# 1st way to do matrix multiplication
arr1 @ arr2

array([[6, 8, 5],
       [6, 8, 5],
       [5, 8, 6]])

In [115]:
# 2nd way to do
np.dot(arr1,arr2)

array([[6, 8, 5],
       [6, 8, 5],
       [5, 8, 6]])

In [116]:
# Matrix multiplication is only possible when
# arr1 = m*n
# arr2 = p*q
# and n=p then result will be m*q

In [117]:
# in python
5/0

ZeroDivisionError: division by zero

In [118]:
# in numpy
arr1/0

<ipython-input-118-d27e07e6bd97>:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [119]:
arr = np.zeros((3,4))

In [120]:
# broadcasting

In [121]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [123]:
a = np.array([1,2,3,4])

In [124]:
a

array([1, 2, 3, 4])

In [125]:
a.ndim

1

In [126]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
a = np.array([[1,2,3,4]])

In [128]:
a

array([[1, 2, 3, 4]])

In [129]:
# Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [130]:
arr1

array([[2, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [131]:
arr1.T

array([[2, 2, 1],
       [1, 1, 2],
       [1, 1, 1]])

In [132]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [133]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])

In [134]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [135]:
np.min(arr1)

1

In [136]:
np.max(arr1)

2