<a href="https://colab.research.google.com/github/CodesbyHim/Numpy/blob/main/Numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [ ]:
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.ndim

1

In [ ]:
b = np.zeros((3,4))

In [ ]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b.ndim

2

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.two(5) #doesn't exists in numpy

AttributeError: module 'numpy' has no attribute 'two'

In [ ]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.ndim

2

In [ ]:
#3 dimensional array

In [ ]:
np.zeros(1)

array([0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.zeros((3,4))
arr.ndim

2

In [ ]:
arr = np.zeros((1,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# 4 dimensional array
arr = np.zeros((1,1,3,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr.ndim

4

In [ ]:
# 5 dimensional array
arr = np.zeros((1,1,1,3,4))
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [ ]:
arr.ndim

5

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr.ndim

2

In [ ]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr -5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [ ]:
arr * 5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1 = np.ones((3,4))

In [ ]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1 - 4

array([[-3., -3., -3., -3.],
       [-3., -3., -3., -3.],
       [-3., -3., -3., -3.]])

In [ ]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# useful in calculating the inverse of matrix

In [ ]:
np.empty((3,4)) #Return a new array of given shape and type, without initializing entries.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.empty((3,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# Optional
# This random module helps us to generate a random number.

import random
random.choice((1,2,3,4,5))

2

In [ ]:
random.choice('Himanshu')

's'

In [ ]:
random.randrange(1,100)

37

In [ ]:
random.random() # a random no. is generated between o(included) and 1(excluded)

0.446176322910259

In [ ]:
lis = [1, 2, 3, 4, 5]
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)

In [ ]:
lis

[2, 3, 1, 5, 4]

In [ ]:
random.uniform(7,14)

7.936268495831724

In [ ]:
# to have random no.s related concepts in numpy
np.array([])

array([], dtype=float64)

In [ ]:
np.random.random_sample()

0.10890107623490719

In [ ]:
np.random.random_sample((5, ))

array([0.86925393, 0.51327338, 0.81748053, 0.16831642, 0.83271329])

In [ ]:
np.random.rand(1)

array([0.62492535])

In [ ]:
np.random.rand(2,3)

array([[0.20727485, 0.74914062, 0.95805166],
       [0.90163101, 0.42959629, 0.59837807]])

In [ ]:
aw = np.random.random_sample((3,4 ))

In [ ]:
aw

array([[0.75304552, 0.71336213, 0.93502162, 0.60267594],
       [0.1671218 , 0.91226475, 0.68286635, 0.65599268],
       [0.62424325, 0.31104113, 0.37945897, 0.9087012 ]])

In [ ]:
aw.ndim

2

In [ ]:
np.random.randn(2,3)

array([[-0.22604842,  0.21055124,  0.30943904],
       [ 0.24505006,  0.63420451,  1.58084357]])

In [ ]:
arr = np.random.randint(1,4, size = (3,4))

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.size

12

In [ ]:
arr

array([[1, 1, 3, 3],
       [3, 3, 3, 1],
       [1, 2, 3, 3]])

In [ ]:
# reshaping the array
arr1 = arr.reshape(2,6)

In [ ]:
arr1.shape

(2, 6)

In [ ]:
arr1.size

12

In [ ]:
#array size will not change,always reshape parameter
# should be multiplication of original array size.

In [ ]:
arr.reshape(1,12)

array([[1, 1, 3, 3, 3, 3, 3, 1, 1, 2, 3, 3]])

In [ ]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [ ]:
arr.reshape(4,3)

array([[1, 1, 3],
       [3, 3, 3],
       [3, 1, 1],
       [2, 3, 3]])

In [ ]:
# Case when you don't know in reshape what should be the column count
arr.reshape(4, -1)

array([[1, 1, 3],
       [3, 3, 3],
       [3, 1, 1],
       [2, 3, 3]])

In [ ]:
arr.reshape(2,-1)

array([[1, 1, 3, 3, 3, 3],
       [3, 1, 1, 2, 3, 3]])

In [ ]:
arr.reshape(2,-100)

array([[1, 1, 3, 3, 3, 3],
       [3, 1, 1, 2, 3, 3]])

In [ ]:
# you know column count but no row count
arr1 = arr.reshape(-1, 3)

In [ ]:
arr1.size

12

In [ ]:
arr.reshape(12,1)

array([[1],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [1],
       [1],
       [2],
       [3],
       [3]])

In [ ]:
arr.reshape(12,1).base # to see the original array

array([[1, 1, 3, 3],
       [3, 3, 3, 1],
       [1, 2, 3, 3]])

In [ ]:
arr.reshape(2,2,3)

array([[[1, 1, 3],
        [3, 3, 3]],

       [[3, 1, 1],
        [2, 3, 3]]])

In [ ]:
arr.reshape(1,2,2,3)

array([[[[1, 1, 3],
         [3, 3, 3]],

        [[3, 1, 1],
         [2, 3, 3]]]])

In [ ]:
arr.reshape(4,3,1) #3 rows 1 column repeated 4 times in the third dimension.

array([[[1],
        [1],
        [3]],

       [[3],
        [3],
        [3]],

       [[3],
        [1],
        [1]],

       [[2],
        [3],
        [3]]])

In [ ]:
# Conditions on array

arr1 = np.random.randint(1,10,(5,6))

In [ ]:
arr1

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5],
       [3, 5, 5, 6, 7, 1],
       [1, 9, 8, 6, 8, 9],
       [4, 8, 6, 5, 2, 9]])

In [ ]:
arr1.shape

(5, 6)

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

30

In [ ]:
arr1 > 3

array([[False,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True]])

In [ ]:
arr1[arr1>3]

array([7, 4, 9, 4, 7, 9, 8, 9, 5, 5, 5, 6, 7, 9, 8, 6, 8, 9, 4, 8, 6, 5,
       9])

In [ ]:
arr1[arr1<3]

array([2, 2, 1, 1, 2])

In [ ]:
arr1

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5],
       [3, 5, 5, 6, 7, 1],
       [1, 9, 8, 6, 8, 9],
       [4, 8, 6, 5, 2, 9]])

In [ ]:
# Accessing elements in the array.
arr1[0]

array([2, 7, 4, 9, 4, 7])

In [ ]:
arr1[1]

array([2, 9, 8, 9, 3, 5])

In [ ]:
arr1[1][0]

2

In [ ]:
arr1

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5],
       [3, 5, 5, 6, 7, 1],
       [1, 9, 8, 6, 8, 9],
       [4, 8, 6, 5, 2, 9]])

In [ ]:
arr1[0:2]

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5]])

In [ ]:
arr1[0:3] #zeroth row, 1st row and 2nd row

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5],
       [3, 5, 5, 6, 7, 1]])

In [ ]:
arr1[0:3,[0,2]] #0 to 2nd row and 0th and 2nd column

array([[2, 4],
       [2, 8],
       [3, 5]])

In [ ]:
# Slicing on both rows and column

In [ ]:
arr1

array([[2, 7, 4, 9, 4, 7],
       [2, 9, 8, 9, 3, 5],
       [3, 5, 5, 6, 7, 1],
       [1, 9, 8, 6, 8, 9],
       [4, 8, 6, 5, 2, 9]])

In [ ]:
arr1[0:3, 1:3]

array([[7, 4],
       [9, 8],
       [5, 5]])

In [ ]:
arr1[0:2,[0,1]]

array([[2, 7],
       [2, 9]])

In [ ]:
arr1[0,[1,3]]

array([7, 9])

In [ ]:
arr1[2:4,[0,3]]

array([[3, 6],
       [1, 6]])

In [ ]:
arr1[2:5]

array([[3, 5, 5, 6, 7, 1],
       [1, 9, 8, 6, 8, 9],
       [4, 8, 6, 5, 2, 9]])

In [ ]:
arr1[2:5,0:2]

array([[3, 5],
       [1, 9],
       [4, 8]])

In [ ]:
# Mathematical calculations on array

arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[1, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [ ]:
arr2

array([[1, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [ ]:
arr1 + arr2 # indexwise addition of arrays

array([[2, 3, 4],
       [4, 2, 3],
       [3, 4, 2]])

In [ ]:
arr1 - arr2 # indexwise subtraction

array([[ 0,  1,  0],
       [ 0,  0, -1],
       [-1,  0,  0]])

In [ ]:
arr1 * arr2 # indexwise multiplication

array([[1, 2, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [ ]:
arr1,arr2

(array([[1, 2, 2],
        [2, 1, 1],
        [1, 2, 1]]),
 array([[1, 1, 2],
        [2, 1, 2],
        [2, 2, 1]]))

In [ ]:
arr1 / arr2 #indexwise division

array([[1. , 2. , 1. ],
       [1. , 1. , 0.5],
       [0.5, 1. , 1. ]])

In [ ]:
# matrix multiplication >>> different from index wise multiplication

# 1st way to do matrix multiplication
arr1 @ arr2

array([[9, 7, 8],
       [6, 5, 7],
       [7, 5, 7]])

In [ ]:
# 2nd way to do
np.dot(arr1,arr2)

array([[9, 7, 8],
       [6, 5, 7],
       [7, 5, 7]])

In [ ]:
# Matrix multiplication is only possible when
# arr1 = m*n
# arr2 = p*q
# and n=p then result will be m*q

In [ ]:
# in python
5/0

ZeroDivisionError: division by zero

In [ ]:
# in numpy
arr1/0

<ipython-input-210-d27e07e6bd97>:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr = np.zeros((3,4))

In [ ]:
# broadcasting

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
a = np.array([[1,2,3,4]])

In [ ]:
a

array([[1, 2, 3, 4]])

In [ ]:
# Transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr1

array([[1, 2, 2],
       [2, 1, 1],
       [1, 2, 1]])

In [ ]:
arr1.T

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [ ]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])

In [ ]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [ ]:
np.min(arr1)

1

In [ ]:
np.max(arr1)

2