<a href="https://colab.research.google.com/github/CodesbyHim/Numpy/blob/main/Numpy_advance_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.zeros(5) #Return a new array of given shape and type, filled with zeros.

In [3]:
a

array([0., 0., 0., 0., 0.])

In [4]:
a.ndim

1

In [5]:
b = np.zeros((3,4))

In [6]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b.ndim

2

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.two(5) #doesn't exists in numpy

AttributeError: module 'numpy' has no attribute 'two'

In [ ]:
np.array([[2,2,2],[2,2,2]])

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

In [ ]:
arr.ndim

In [ ]:
#3 dimensional array

In [ ]:
np.zeros(1)

In [ ]:
np.zeros((2,3))

In [ ]:
arr = np.zeros((3,4))
arr.ndim

In [ ]:
arr = np.zeros((1,3,4))
arr

In [ ]:
# 4 dimensional array
arr = np.zeros((1,1,3,4))
arr

In [ ]:
arr.ndim

In [ ]:
# 5 dimensional array
arr = np.zeros((1,1,1,3,4))
arr

In [ ]:
arr.ndim

In [ ]:
arr = np.zeros((3,4))

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr.ndim

In [ ]:
arr + 5

In [ ]:
arr

In [ ]:
arr -5

In [ ]:
arr * 5

In [ ]:
arr1 = np.ones((3,4))

In [ ]:
arr1

In [ ]:
arr1 - 4

In [ ]:
np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3,4)

In [ ]:
# useful in calculating the inverse of matrix

In [ ]:
np.empty((3,4)) #Return a new array of given shape and type, without initializing entries.

In [ ]:
np.eye(3, dtype = int)

In [ ]:
np.empty((3,4))

In [ ]:
# Optional
# This random module helps us to generate a random number.

import random
random.choice((1,2,3,4,5))

In [ ]:
random.choice('Himanshu')

In [ ]:
random.randrange(1,100)

In [ ]:
random.random() # a random no. is generated between o(included) and 1(excluded)

In [ ]:
lis = [1, 2, 3, 4, 5]
lis

In [ ]:
random.shuffle(lis)

In [ ]:
lis

In [ ]:
random.uniform(7,14)

In [ ]:
# to have random no.s related concepts in numpy
np.array([])

In [ ]:
np.random.random_sample()

In [ ]:
np.random.random_sample((5, ))

In [ ]:
np.random.rand(1)

In [ ]:
np.random.rand(2,3)

In [ ]:
aw = np.random.random_sample((3,4 ))

In [ ]:
aw

In [ ]:
aw.ndim

In [ ]:
np.random.randn(2,3)

In [ ]:
arr = np.random.randint(1,4, size = (3,4))

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr

In [ ]:
# reshaping the array
arr1 = arr.reshape(2,6)

In [ ]:
arr1.shape

In [ ]:
arr1.size

In [ ]:
#array size will not change,always reshape parameter
# should be multiplication of original array size.

In [ ]:
arr.reshape(1,12)

In [ ]:
arr.reshape(3,3)

In [ ]:
arr.reshape(4,3)

In [ ]:
# Case when you don't know in reshape what should be the column count
arr.reshape(4, -1)

In [ ]:
arr.reshape(2,-1)

In [ ]:
arr.reshape(2,-100)

In [ ]:
# you know column count but no row count
arr1 = arr.reshape(-1, 3)

In [ ]:
arr1.size

In [ ]:
arr.reshape(12,1)

In [ ]:
arr.reshape(12,1).base # to see the original array

In [ ]:
arr.reshape(2,2,3)

In [ ]:
arr.reshape(1,2,2,3)

In [ ]:
arr.reshape(4,3,1) #3 rows 1 column repeated 4 times in the third dimension.

In [ ]:
# Conditions on array

arr1 = np.random.randint(1,10,(5,6))

In [ ]:
arr1

In [ ]:
arr1.shape

In [ ]:
arr1.ndim

In [ ]:
arr1.size

In [ ]:
arr1 > 3

In [ ]:
arr1[arr1>3]

In [ ]:
arr1[arr1<3]

In [ ]:
arr1

In [ ]:
# Accessing elements in the array.
arr1[0]

In [ ]:
arr1[1]

In [ ]:
arr1[1][0]

In [ ]:
arr1

In [ ]:
arr1[0:2]

In [ ]:
arr1[0:3] #zeroth row, 1st row and 2nd row

In [ ]:
arr1[0:3,[0,2]] #0 to 2nd row and 0th and 2nd column

In [ ]:
# Slicing on both rows and column

In [ ]:
arr1

In [ ]:
arr1[0:3, 1:3]

In [ ]:
arr1[0:2,[0,1]]

In [ ]:
arr1[0,[1,3]]

In [ ]:
arr1[2:4,[0,3]]

In [ ]:
arr1[2:5]

In [ ]:
arr1[2:5,0:2]

In [ ]:
# Mathematical calculations on array

arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr1 + arr2 # indexwise addition of arrays

In [ ]:
arr1 - arr2 # indexwise subtraction

In [ ]:
arr1 * arr2 # indexwise multiplication

In [ ]:
arr1,arr2

In [ ]:
arr1 / arr2 #indexwise division

In [ ]:
# matrix multiplication >>> different from index wise multiplication

# 1st way to do matrix multiplication
arr1 @ arr2

In [ ]:
# 2nd way to do
np.dot(arr1,arr2)

In [ ]:
# Matrix multiplication is only possible when
# arr1 = m*n
# arr2 = p*q
# and n=p then result will be m*q

In [ ]:
# in python
5/0

In [ ]:
# in numpy
arr1/0

In [ ]:
arr = np.zeros((3,4))

In [ ]:
# broadcasting

In [ ]:
arr

In [ ]:
arr + 5

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
arr + a

In [ ]:
a = np.array([[1,2,3,4]])

In [ ]:
a

In [ ]:
# Transpose
a.T

In [ ]:
arr1

In [ ]:
arr1.T

In [ ]:
np.sqrt(arr1)

In [ ]:
np.log10(arr1)

In [ ]:
np.exp(arr1)

In [ ]:
np.min(arr1)

In [ ]:
np.max(arr1)