<a href="https://colab.research.google.com/github/CodesbyHim/NumPy/blob/main/NumPy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

# Code

import numpy as np
arr=np.arange(6)
print("Array:",arr)
print("Data type: ", arr.dtype)

Array: [0 1 2 3 4 5]
Data type:  int64


In [4]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
#    arr = np.array([1.5, 2.6, 3.7])

# Code

import numpy as np
arr = np.array([1.5, 2.6, 3.7])

is_float64 = arr.dtype == np.float64
print("Is the data type float64?", is_float64)

Is the data type float64? True


In [5]:
#  3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

# Code

import numpy as np
complex_num=[2+3j,9+4j,1+2j]
arr=np.array(complex_num,dtype=np.complex128)

print("Array",arr)
print("Data type:",arr.dtype)

Array [2.+3.j 9.+4.j 1.+2.j]
Data type: complex128


In [6]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

# Code

import numpy as np

arr = np.array([1, 2, 3, 4])
arr_float32 = arr.astype('float32')

print(arr_float32.dtype)

float32


In [7]:
#  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

# Code

import numpy as np

arr = np.array([1.123456789, 2.987654321, 3.141592653], dtype='float64')

print("Original array data type:", arr.dtype)
arr_float32 = arr.astype('float32')

print("Converted array data type:", arr_float32.dtype)

Original array data type: float64
Converted array data type: float32


In [8]:
#  6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

#  Code

import numpy as np

def array_attributes(arr):
    size=np.shape(arr)
    shape=np.size(arr)
    data_type = arr.dtype
    return size,shape,data_type
arr=np.array([1,2,3,4,5])
size,shape,data_type=array_attributes(arr)
print("shape:",shape)
print("size:",size)
print("data type:",data_type)


shape: 5
size: (5,)
data type: int64


In [9]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

# Code

import numpy as np

def array_dimension (arr):
    dimension =arr.ndim
    return dimension
arr=np.array([[1,2,3],[4,5,6]])
dimension =array_dimension(arr)
print("Dimensionality:",dimension)


Dimensionality: 2


In [10]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

# Code

import numpy as np

def item_size_info(arr):
    if isinstance(arr, np.ndarray):
        item_size = arr.itemsize
        total_size = arr.nbytes
        print(f"Item size: {item_size} bytes")
        print(f"Total size: {total_size} bytes")
    else:
        print("Invalid input. Please provide a NumPy array.")

arr = np.array([1, 2, 3, 4, 5])
item_size_info(arr)


Item size: 8 bytes
Total size: 40 bytes


In [11]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

# Code

import numpy as np

def array_strides(input_array):
    if isinstance(input_array, np.ndarray):
        return input_array.strides
    else:
        raise ValueError("Input is not a NumPy array")

my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_strides(my_array))

(24, 8)


In [12]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

# Code

import numpy as np

def array_strides(input_array):
    if isinstance(input_array, np.ndarray):
        return input_array.strides
    else:
        raise ValueError("Input is not a NumPy array")

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print("My array:")
print(my_array)
print("\nStrides of my array:")
print(array_strides(my_array))

My array:
[[1 2 3]
 [4 5 6]]

Strides of my array:
(24, 8)


In [13]:
#  11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

# Code

import numpy as np

def create_zeros_array(n):

    return np.zeros(n)

print(create_zeros_array(int(input())))

6
[0. 0. 0. 0. 0. 0.]


In [14]:
#  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`

# Code

import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

rows = 2
cols = 3
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#  13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step`.

# Code

import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[0 2 4 6 8]


In [16]:
#  14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as  arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

# Code

import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage:
start = 0.0
stop = 1.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(linear_space)

[0.   0.25 0.5  0.75 1.  ]


In [17]:
#  15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

#  Code

import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#  16. Write a function that takes a Python list and converts it into a NumPy array.

#  Code

import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)

lst = [1, 2, 3]
numpy_array = list_to_numpy_array(lst)
print(numpy_array)

[1 2 3]


In [19]:
#  17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

#  Code

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

new_arr = arr.view()

print("Original array:")
print(arr)
print("\nNew array:")
print(new_arr)

new_arr[0] = 10
print("\nOriginal array after modifying new array:")
print(arr)

Original array:
[1 2 3 4 5]

New array:
[1 2 3 4 5]

Original array after modifying new array:
[10  2  3  4  5]


In [20]:
#  18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

#      Code

import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

result = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:")
print(result)

result = concatenate_arrays(array1, array2.T, axis=1)
print("\nConcatenated along axis 1:")
print(result)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]]

Concatenated along axis 1:
[[1 2 5]
 [3 4 6]]


In [21]:
# 19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

# Code

import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8], [9, 10]])

array2_extended = np.concatenate((array2, np.zeros((array2.shape[0], 1))), axis=1)

result = np.concatenate((array1, array2_extended), axis=1)

print(result)

[[ 1.  2.  3.  7.  8.  0.]
 [ 4.  5.  6.  9. 10.  0.]]


In [22]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

# Code

import numpy as np

def stack_arrays_vertically(arrays_list):

    stacked_array = np.vstack(arrays_list)
    return stacked_array

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.array([7, 8, 9])

stacked_array = stack_arrays_vertically([array1, array2, array3])
print(stacked_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#  21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)  with a given step size.

#  Code

import numpy as np

def create_integer_array(start, end, step=1):

    if step == 0:
        raise ValueError("Step size cannot be zero.")

    integer_array = np.arange(start, end + 1, step)
    return integer_array
integer_array = create_integer_array(0, 10, 2)
print(integer_array)

[ 0  2  4  6  8 10]


In [24]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

#     Code

import numpy as np

def generate_equally_spaced_values(start, end, num_values):

    if num_values <= 0:
        raise ValueError("Number of values must be greater than zero.")

    equally_spaced_values = np.linspace(start, end, num_values)
    return equally_spaced_values

equally_spaced_values = generate_equally_spaced_values(0, 1, 10)
print(equally_spaced_values)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [25]:
#  23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

#    Code

import numpy as np

def generate_log_array():
    return np.logspace(1, 3, 5, endpoint=True)
print(generate_log_array())

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [26]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

# Code

import numpy as np
import pandas as pd

np_array = np.random.randint(1, 101, size=(5, 3))

print("NumPy Array:")
print(np_array)

df = pd.DataFrame(np_array, columns=['Column_1', 'Column_2', 'Column_3'])

print("\nPandas DataFrame:")
print(df)

NumPy Array:
[[ 9 93 77]
 [86 72 62]
 [ 4 94 63]
 [ 6  8 86]
 [ 2 53 59]]

Pandas DataFrame:
   Column_1  Column_2  Column_3
0         9        93        77
1        86        72        62
2         4        94        63
3         6         8        86
4         2        53        59


In [27]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific columnwith zeros. Use NumPy operations within the Pandas DataFrame.

# Code

import pandas as pd
import numpy as np

def replace_negative_with_zeros(dataframe, column):

    dataframe[column] = np.where(dataframe[column] < 0, 0, dataframe[column])
    return dataframe

# Example usage
data = {'A': [-1, 2, -3, 4],
        'B': [5, -6, 7, -8]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negative_with_zeros(df, 'A')

print("\nDataFrame with negative values replaced by zeros:")
print(df)



Original DataFrame:
   A  B
0 -1  5
1  2 -6
2 -3  7
3  4 -8

DataFrame with negative values replaced by zeros:
   A  B
0  0  5
1  2 -6
2  0  7
3  4 -8


In [28]:
# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

# Code

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print("The third element of the array is:", third_element)


The third element of the array is: 30


In [29]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

# Code

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element_at_1_2 = arr_2d[1, 2]
print("Element at index (1, 2) is:", element_at_1_2)


Element at index (1, 2) is: 6


In [30]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

# Code

import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5

result = arr[mask]

print("Elements greater than 5:", result)

Elements greater than 5: [ 8 10  7]


In [31]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Code

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sliced_arr = arr[2:6]
print("The elements from index 2 to 5 (inclusive) from the array are:", sliced_arr)

The elements from index 2 to 5 (inclusive) from the array are: [3 4 5 6]


In [32]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
# arr_2d = np.array([[1, 2, 3],
                   # [4, 5, 6],
                   # [7, 8, 9]])

# Code

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:3]

print(sub_array)


[[2 3]
 [5 6]]


In [33]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

# Code

import numpy as np

def extract_elements(arr_2d, indices):
    extracted_elements = arr_2d[tuple(indices.T.tolist())]
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

indices = np.array([[0, 0],
                      [1, 2],
                      [2, 1]])

extracted_elements = extract_elements(arr_2d, indices)

print("The extracted elements in the specified order are:", extracted_elements)

The extracted elements in the specified order are: [1 6 8]


In [34]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

# Code

import numpy as np

def filter_greater_than(arr, threshold):

    filtered_arr = arr[arr > threshold]

    return filtered_arr
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

filtered_arr = filter_greater_than(arr, 5)

print("The elements greater than 5 are:", filtered_arr)

The elements greater than 5 are: [6 7 8 9]


In [35]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

# Code

import numpy as np

def extract_elements_3d(array, x_indices, y_indices, z_indices):
    return array[x_indices, y_indices, z_indices]

array_3d = np.random.randint(1, 100, size=(4, 4, 4))
print("Original 3D array:")
print(array_3d)

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 2, 3])
z_indices = np.array([3, 0, 1])

extracted_elements = extract_elements_3d(array_3d, x_indices, y_indices, z_indices)
print("\nExtracted elements:")
print(extracted_elements)

Original 3D array:
[[[27 68 29 20]
  [63 55 16 89]
  [49 24 42 42]
  [54 33 53 15]]

 [[99 44 79 89]
  [81 13 41 76]
  [ 8  2 89 19]
  [42 73  9 11]]

 [[78 61 51 46]
  [33 22 38 31]
  [23 37  9 30]
  [62 81 25 14]]

 [[41 82  4 62]
  [ 2 16 27 56]
  [67 62 83 16]
  [48 99 96 97]]]

Extracted elements:
[89  8 81]


In [36]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

# Code

import numpy as np

def filter_two_conditions(arr, condition1, condition2):
    filtered_arr = arr[(condition1) & (condition2)]
    return filtered_arr

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = (arr > 3)
condition2 = (arr % 2 == 0)
filtered_arr = filter_two_conditions(arr, condition1, condition2)
print("The elements greater than 3 and even are:", filtered_arr)

The elements greater than 3 and even are: [4 6 8]


In [37]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

# Code

import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
extracted_elements = extract_elements_2d(arr, row_indices, col_indices)
print("The extracted elements are:", extracted_elements)

The extracted elements are: [3 5 7]


In [38]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

# Code

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print("The array after adding 5 to each element is:")
print(result)

The array after adding 5 to each element is:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [39]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

# Code

import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

result = arr2 * arr1.T

print("\nResult of broadcasting multiplication:")
print(result)

Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of broadcasting multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [40]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

# Code

import numpy as np

arr1 = np.array([[2, 3, 4]])
arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

result = arr2 * arr1.T

print("\nResult of broadcasting multiplication:")
print(result)

Array arr1:
[[2 3 4]]

Array arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of broadcasting multiplication:
[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [41]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

# Code

import numpy as np

arr1 = np.array([[1],
                [2],
                [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2

print("The resulting array after adding arr1 and arr2 is:")
print(result)

The resulting array after adding arr1 and arr2 is:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [42]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

# Code

import numpy as np

arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2 = np.array([
    [7, 8],
    [9, 10]
])

print("Array arr1:")
print(arr1)
print("\nArray arr2:")
print(arr2)

arr2_expanded = np.expand_dims(arr2, axis=2)
arr1_expanded = np.expand_dims(arr1, axis=1)

result = arr1_expanded * arr2_expanded

print("\nResult of broadcasting multiplication:")
print(result)

Array arr1:
[[1 2 3]
 [4 5 6]]

Array arr2:
[[ 7  8]
 [ 9 10]]

Result of broadcasting multiplication:
[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


In [43]:
# 41. Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

# Code

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column wise mean
col_mean = np.mean(arr, axis=0)

print("The column wise mean of the array is:")
print(col_mean)

The column wise mean of the array is:
[2.5 3.5 4.5]


In [44]:
# 42. Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

# Code

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

row_max = np.max(arr, axis=1)

print("The maximum value in each row of the array is:")
print(row_max)

The maximum value in each row of the array is:
[3 6]


In [45]:
# 43. For the given array, find indices of maximum value in each column.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

# Code

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
col_max_indices = np.argmax(arr, axis=0)

print("The indices of the maximum value in each column of the array are:")
print(col_max_indices)

The indices of the maximum value in each column of the array are:
[1 1 1]


In [46]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])

# Code

import numpy as np

def moving_sum(arr, window_size=2):
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1))
    for i in range(arr.shape[1] - window_size + 1):
        result[:, i] = np.sum(arr[:, i:i+window_size], axis=1)
    return result

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(arr)

result = moving_sum(arr, window_size=2)
print("\nMoving sum along rows with window size 2:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows with window size 2:
[[ 3.  5.]
 [ 9. 11.]]


In [47]:
# 45. In the given array, check if all elements in each column are even.
# arr = np.array([[2, 4, 6], [3, 5, 7]])

# Code

import numpy as np

arr = np.array([[2, 4, 6],
                [3, 5, 7]])

is_even = np.all(arr % 2 == 0, axis=0)

print("The result of checking if all elements in each column are even is:")
print(is_even)

The result of checking if all elements in each column are even is:
[False False False]


In [48]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])

# Code

import numpy as np

def reshape_matrix(arr, m, n):

    reshaped_matrix = np.reshape(arr, (m, n))

    return reshaped_matrix

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_matrix = reshape_matrix(original_array, 2, 3)

print("The reshaped matrix is:")
print(reshaped_matrix)

The reshaped matrix is:
[[1 2 3]
 [4 5 6]]


In [49]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Code

import numpy as np

def flatten_matrix(matrix):

    flattened_array = np.ravel(matrix)

    return flattened_array

input_matrix = np.array([[1, 2, 3],
                          [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("The flattened array is:")
print(flattened_array)

The flattened array is:
[1 2 3 4 5 6]


In [50]:
# 48. Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]])
# array2 = np.array([[5, 6], [7, 8]])

# Code

import numpy as np

def concatenate_arrays(array1, array2, axis=0):

    output_array = np.concatenate((array1, array2), axis=axis)
    return output_array

array1 = np.array([[1, 2],
                      [3, 4]])

array2 = np.array([[5, 6],
                      [7, 8]])
output_array = concatenate_arrays(array1, array2)

print("The output array after concatenation along the default axis (axis=0) is:")
print(output_array)

output_array = concatenate_arrays(array1, array2, axis=1)

print("The output array after concatenation along the other axis (axis=1) is:")
print(output_array)

The output array after concatenation along the default axis (axis=0) is:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
The output array after concatenation along the other axis (axis=1) is:
[[1 2 5 6]
 [3 4 7 8]]


In [51]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
#     original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Code

import numpy as np

def split_array(arr, num_splits, axis=0):

    return np.array_split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(original_array)

sub_arrays_axis_0 = split_array(original_array, 3, axis=0)
print("\nSplit array along axis 0:")
for i, sub_array in enumerate(sub_arrays_axis_0):
    print(f"Sub-array {i}:\n{sub_array}")

sub_arrays_axis_1 = split_array(original_array, 3, axis=1)
print("\nSplit array along axis 1:")
for i, sub_array in enumerate(sub_arrays_axis_1):
    print(f"Sub-array {i}:\n{sub_array}")

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Split array along axis 0:
Sub-array 0:
[[1 2 3]]
Sub-array 1:
[[4 5 6]]
Sub-array 2:
[[7 8 9]]

Split array along axis 1:
Sub-array 0:
[[1]
 [4]
 [7]]
Sub-array 1:
[[2]
 [5]
 [8]]
Sub-array 2:
[[3]
 [6]
 [9]]


In [52]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
#     original_array = np.array([1, 2, 3, 4, 5])
#     indices_to_insert = [2, 4]
#     values_to_insert = [10, 11]
#     indices_to_delete = [1, 3]

# Code

import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):

    modified_array = np.insert(arr, indices_to_insert, values_to_insert)

    modified_array = np.delete(modified_array, indices_to_delete)

    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

print("Original array:")
print(original_array)

result = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("\nModified array after insertion and deletion:")
print(result)

Original array:
[1 2 3 4 5]

Modified array after insertion and deletion:
[ 1 10  4 11  5]


In [53]:
# 51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

# Code

import numpy as np

arr1 = np.random.randint(1, 100, size=10)
print("Array arr1:")
print(arr1)

arr2 = np.arange(1, 11)
print("\nArray arr2:")
print(arr2)

result = arr1 + arr2
print("\nResult of element-wise addition:")
print(result)

Array arr1:
[29 98 22 20 73 12 94 72 86 65]

Array arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise addition:
[ 30 100  25  24  78  18 101  80  95  75]


In [54]:
# 52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

# Code

import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [10  9  8  7  6  5  4  3  2  1]
Array arr2:  [ 1  2  3  4  5  6  7  8  9 10]
Result array:  [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [55]:
# 53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.

# Code

import numpy as np

arr1 = np.random.randint(1, 10, size=(5,))
arr2 = np.arange(1, 6)
result = arr1 * arr2[:, np.newaxis]

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [5 7 3 4 8]
Array arr2:  [1 2 3 4 5]
Result array:  [[ 5  7  3  4  8]
 [10 14  6  8 16]
 [15 21  9 12 24]
 [20 28 12 16 32]
 [25 35 15 20 40]]


In [56]:
# 54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

# Code

import numpy as np

arr1 = np.arange(2, 12, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2[:, np.newaxis]

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [ 2  4  6  8 10]
Array arr2:  [1 2 3 4 5]
Result array:  [[ 2.          4.          6.          8.         10.        ]
 [ 1.          2.          3.          4.          5.        ]
 [ 0.66666667  1.33333333  2.          2.66666667  3.33333333]
 [ 0.5         1.          1.5         2.          2.5       ]
 [ 0.4         0.8         1.2         1.6         2.        ]]


In [57]:
# 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

# Code

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

result = np.power(arr1, arr2)

print("Array arr1: ", arr1)
print("Array arr2: ", arr2)
print("Result array: ", result)

Array arr1:  [1 2 3 4 5]
Array arr2:  [5 4 3 2 1]
Result array:  [ 1 16 27 16  5]


In [58]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#     arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Code

import numpy as np

def count_substring(arr, substring):

    return np.sum(np.char.find(arr, substring) >= 0)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

result = count_substring(arr, substring)

print("Array: ", arr)
print("Substring: ", substring)
print("Number of occurrences: ", result)

Array:  ['hello' 'world' 'hello' 'numpy' 'hello']
Substring:  hello
Number of occurrences:  3


In [59]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
#     arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Code

import numpy as np

def extract_uppercase_characters(arr):

    uppercase_characters = []
    for string in arr:
        for char in string:
            if char.isupper():
                uppercase_characters.append(char)
    return uppercase_characters

string_array = np.array(["Hello World", "NumPy Arrays", "OpenAI GPT-3", "Data Science"])
print("Original array of strings:")
print(string_array)

uppercase_characters = extract_uppercase_characters(string_array)
print("\nUppercase characters extracted:")
print(uppercase_characters)

Original array of strings:
['Hello World' 'NumPy Arrays' 'OpenAI GPT-3' 'Data Science']

Uppercase characters extracted:
['H', 'W', 'N', 'P', 'A', 'O', 'A', 'I', 'G', 'P', 'T', 'D', 'S']


In [60]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Code

import numpy as np

def replace_substring(arr, old_substring, new_substring):

    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = replace_substring(arr, 'apple', 'orange')

print("Array: ", arr)
print("Replaced array: ", result)

Array:  ['apple' 'banana' 'grape' 'pineapple']
Replaced array:  ['orange' 'banana' 'grape' 'pineorange']


In [61]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
#     arr1 = np.array(['Hello', 'World'])
#     arr2 = np.array(['Open', 'AI'])

# Code


import numpy as np

def concatenate_strings(arr1, arr2):

    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)

print("Array 1: ", arr1)
print("Array 2: ", arr2)
print("Concatenated array: ", result)

Array 1:  ['Hello' 'World']
Array 2:  ['Open' 'AI']
Concatenated array:  ['HelloOpen' 'WorldAI']


In [62]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
#     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Code

import numpy as np

def longest_string_length(arr):

    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

result = longest_string_length(arr)

print("Array: ", arr)
print("Length of longest string: ", result)

Array:  ['apple' 'banana' 'grape' 'pineapple']
Length of longest string:  9


In [63]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

# Code

import numpy as np

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print("Dataset: ", dataset)
print("Mean: ", mean)
print("Median: ", median)
print("Variance: ", variance)
print("Standard Deviation: ", std_deviation)

Dataset:  [188 206 867 733 689 270 129 130 715 271 945 455 828 942 513 446 784 583
 948 165 136 703 202 465 720 578 703 336 532  85 477 227 837 398 521 705
 584 876 634 490  76 275  33 145 947 788 488  65 293 485 763 133 163 677
 979 302 412 826 345 183 795 437 463 316 343 564  36   4 344  60 657  29
 189 535 217 106 174 504 601 103 926 528 449 329 889 138 102 351 765  86
 627 870  12  59   8 632 742  29 661 811]
Mean:  448.85
Median:  459.0
Variance:  82476.7075
Standard Deviation:  287.18758242653877


In [64]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

# Code

import numpy as np

dataset = np.random.randint(1, 101, size=50)

q1 = np.percentile(dataset, 25)
q3 = np.percentile(dataset, 75)

print("Dataset: ", dataset)
print("25th percentile: ", q1)
print("75th percentile: ", q3)

Dataset:  [47 13 68  2 46 49 54 80 29 20 48 27 26 60 80 48 25 98 29 43 18 54 90  6
 22 16 88 75 86 11 24 20 17 11 91 29 19 42 73 39 38 30 28 40 67  1 85 62
 66 44]
25th percentile:  22.5
75th percentile:  65.0


In [65]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

# Code

import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 3, 5, 6, 7])

result = np.corrcoef(array1, array2)[0, 1]

print("Array 1: ", array1)
print("Array 2: ", array2)
print("Correlation coefficient: ", result)

Array 1:  [1 2 3 4 5]
Array 2:  [2 3 5 6 7]
Correlation coefficient:  0.9912407071619304


In [66]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

# Code

import numpy as np

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)

result = np.dot(matrix_a, matrix_b)

print("\nResult of Matrix Multiplication:")
print(result)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of Matrix Multiplication:
[[19 22]
 [43 50]]


In [67]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

# Code

import numpy as np

array = np.random.randint(10, 1001, size=50)

p10 = np.percentile(array, 10)
p50 = np.percentile(array, 50)
p90 = np.percentile(array, 90)

q1 = np.percentile(array, 25)
q3 = np.percentile(array, 75)

print("Array:")
print(array)
print("\nPercentiles:")
print("10th percentile: ", p10)
print("50th percentile (median): ", p50)
print("90th percentile: ", p90)
print("\nQuartiles:")
print("1st quartile: ", q1)
print("3rd quartile: ", q3)

Array:
[501 209 283 949 284 249 355 954 146  45 779 624 742 195 142  67 150 136
  91 808 963 221 734  87 685 641 334 585 675 937  20  18 469  23 703 427
 408 730 847 448 105 409 210 418 632 992 567 365 231  58]

Percentiles:
10th percentile:  66.10000000000001
50th percentile (median):  408.5
90th percentile:  856.0000000000001

Quartiles:
1st quartile:  161.25
3rd quartile:  682.5


In [68]:
# 66. Create a NumPy array of integers and find the index of a specific element.

# Code

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

index = np.where(array == 7)[0][0]

print("Array:")
print(array)
print("\nIndex of 7: ", index)

Array:
[ 1  2  3  4  5  6  7  8  9 10]

Index of 7:  6


In [69]:
# 67. Generate a random NumPy array and sort it in ascending order.

# Code

import numpy as np

array = np.random.rand(10)

sorted_array = np.sort(array)

print("Original array:")
print(array)
print("\nSorted array:")
print(sorted_array)

Original array:
[0.58869812 0.34149151 0.8367626  0.65065021 0.83978471 0.49704115
 0.42809142 0.36142838 0.00251829 0.52438666]

Sorted array:
[0.00251829 0.34149151 0.36142838 0.42809142 0.49704115 0.52438666
 0.58869812 0.65065021 0.8367626  0.83978471]


In [70]:
# 68. Filter elements >20 in the given NumPy array.
#     arr = np.array([12, 25, 6, 42, 8, 30])

# Code

import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[12 25  6 42  8 30]

Filtered array:
[25 42 30]


In [71]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
#     arr = np.array([1, 5, 8, 12, 15])

# Code

import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]
print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[ 1  5  8 12 15]

Filtered array:
[12 15]


In [72]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#     arr = np.array([10, 20, 30, 40, 50])

# Code

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Original array:")
print(arr)
print("\nFiltered array:")
print(filtered_arr)

Original array:
[10 20 30 40 50]

Filtered array:
[20 30 40]


In [73]:
# 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
#     arr = np.array([1, 2, 3])

# Code

import numpy as np
arr = np.array([1, 2, 3])
print("Original array:")
print(arr)

byte_order = arr.dtype.byteorder
print("\nByte order of the array:")
print(byte_order)

if byte_order == '<':
    print("Little-endian")
elif byte_order == '>':
    print("Big-endian")
else:
    print("Native byte order (depends on system endianness)")

Original array:
[1 2 3]

Byte order of the array:
=
Native byte order (depends on system endianness)


In [74]:
# 72. For the given NumPy array, perform byte swapping in place using 'byteswap()`.
#     arr = np.array ([1, 2, 3], dtype=np.int32)

# Code

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

arr.byteswap(True)
print("\nArray after byte swapping:")
print(arr)

Original array:
[1 2 3]

Array after byte swapping:
[16777216 33554432 50331648]


In [75]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
#     arr = np.array ([1, 2, 3], dtype=np.int32)

# Code

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Array with swapped byte order:", swapped_arr)


Original array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [76]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
#     arr = np.array ([1, 2, 3], dtype=np.int32)

# Code

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

if arr.dtype.byteorder == '<' or (arr.dtype.byteorder == '=' and np.little_endian):
    swapped_array = arr.newbyteorder()
    print("\nSystem is little-endian. Swapping byte order.")
else:
    swapped_array = arr.copy()
    print("\nSystem is big-endian. No need to swap byte order.")

print("\nArray after conditional byte swapping:")
print(swapped_array)

Original array:
[1 2 3]

System is little-endian. Swapping byte order.

Array after conditional byte swapping:
[16777216 33554432 50331648]


In [77]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using`dtype` attribute 'byteorder`.
#     arr = np.array ([1, 2, 3], dtype=np.int32)

# Code

import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(arr)

if arr.dtype.byteorder == '<' or (arr.dtype.byteorder == '=' and np.little_endian):
    print("\nSystem is little-endian. Byte swapping is necessary.")
else:
    print("\nSystem is big-endian. Byte swapping is not necessary.")

Original array:
[1 2 3]

System is little-endian. Byte swapping is necessary.


In [78]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

# Code

import numpy as np
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()
copy_arr[0] = 100

print("Original arr1:", arr1)
print("Modified copy_arr:", copy_arr)


Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [79]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from  the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

# Code

import numpy as np

matrix = np.random.randint(0, 10, size=(3, 3))
view_slice = matrix[:2, :2]

print("Original matrix:")
print(matrix)

print("\nSlice from the original matrix:")
print(view_slice)

view_slice[0, 0] = 99

print("\nModified slice:")
print(view_slice)

print("\nOriginal matrix after modifying the slice:")
print(matrix)


Original matrix:
[[2 2 9]
 [9 2 4]
 [3 0 5]]

Slice from the original matrix:
[[2 2]
 [9 2]]

Modified slice:
[[99  2]
 [ 9  2]]

Original matrix after modifying the slice:
[[99  2  9]
 [ 9  2  4]
 [ 3  0  5]]


In [80]:
# 78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

# Code

import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
print("Original array (array_a):")
print(array_a)

view_b = array_a[1:3, :]
print("\nExtracted slice (view_b):")
print(view_b)

view_b += 5
print("\nModified slice (view_b) after broadcasting addition of 5:")
print(view_b)

print("\nOriginal array (array_a) after modifying the slice:")
print(array_a)

Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Extracted slice (view_b):
[[4 5 6]
 [7 8 9]]

Modified slice (view_b) after broadcasting addition of 5:
[[ 9 10 11]
 [12 13 14]]

Original array (array_a) after modifying the slice:
[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]


In [81]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

# Code

import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
print("Original array (orig_array):")
print(orig_array)

reshaped_view = orig_array.reshape(4, 2)
print("\nReshaped view (reshaped_view):")
print(reshaped_view)

reshaped_view[0, 0] = 999
print("\nModified view (reshaped_view):")
print(reshaped_view)

print("\nOriginal array after modifying the view:")
print(orig_array)

Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified view (reshaped_view):
[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]]

Original array after modifying the view:
[[999   2   3   4]
 [  5   6   7   8]]


In [82]:
# 80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

# Code

import numpy as np

data = np.random.randint(1, 10, size=(3, 4))
print("Original array (data):")
print(data)

data_copy = data[data > 5].copy()
print("\nCopy of elements greater than 5 (data_copy):")
print(data_copy)

data_copy[0] = 999
print("\nModified copy (data_copy):")
print(data_copy)

print("\nOriginal array (data) after modifying the copy:")
print(data)

Original array (data):
[[6 4 7 1]
 [6 8 2 2]
 [7 1 3 8]]

Copy of elements greater than 5 (data_copy):
[6 7 6 8 7 8]

Modified copy (data_copy):
[999   7   6   8   7   8]

Original array (data) after modifying the copy:
[[6 4 7 1]
 [6 8 2 2]
 [7 1 3 8]]


In [83]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

# Code

import numpy as np

shape = (3, 3)
A = np.random.randint(0, 10, shape)
B = np.random.randint(0, 10, shape)

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition Result (A + B):")
print(addition_result)
print("\nSubtraction Result (A - B):")
print(subtraction_result)


Matrix A:
[[2 5 8]
 [1 3 8]
 [9 2 4]]

Matrix B:
[[2 6 8]
 [5 3 4]
 [6 8 7]]

Addition Result (A + B):
[[ 4 11 16]
 [ 6  6 12]
 [15 10 11]]

Subtraction Result (A - B):
[[ 0 -1  0]
 [-4  0  4]
 [ 3 -6 -3]]


In [84]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

# Code

import numpy as np

C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)

result = np.dot(C, D)

print("\nResult of matrix multiplication:")
print(result)

Matrix C:
[[9 5]
 [6 4]
 [2 5]]

Matrix D:
[[6 6 3 4]
 [9 4 2 7]]

Result of matrix multiplication:
[[99 74 37 71]
 [72 52 26 52]
 [57 32 16 43]]


In [85]:
# 83. Create a matrix E and find its transpose.

# Code

import numpy as np

E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matrix E:")
print(E)

E_T = E.T

print("Transpose of matrix E:")
print(E_T)

Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [86]:
# 84. Generate a square matrix `F` and compute its determinant.

# Code

import numpy as np

size = 4
F = np.random.randint(0, 10, (size, size))

determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of F:", determinant_F)


Matrix F:
[[2 1 7 5]
 [3 1 2 3]
 [6 8 0 4]
 [1 0 1 4]]

Determinant of F: 299.99999999999994


In [87]:
# 85. Create a square matrix `G` and find its inverse.

# Code

import numpy as np

G = np.random.randint(1, 10, size=(3, 3))
print("Matrix G:")
print(G)

inverse_G = np.linalg.inv(G)

print("\nInverse of matrix G:")
print(inverse_G)


Matrix G:
[[8 4 1]
 [8 8 6]
 [9 5 1]]

Inverse of matrix G:
[[ 0.91666667 -0.04166667 -0.66666667]
 [-1.91666667  0.04166667  1.66666667]
 [ 1.33333333  0.16666667 -1.33333333]]
