<a href="https://colab.research.google.com/github/CodesbyHim/Numpy/blob/main/Numpy_advance_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [3]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [4]:
arr2

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [5]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([1, 2, 2, 1, 2, 1, 2, 1, 2])

In [6]:
# Expand dimension
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr.ndim

1

In [8]:
np.expand_dims(arr, axis = 0) # increases the dimension by 1 at provided axis.

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr, axis = 1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr, axis = 1).ndim

2

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr = np.zeros((3,4))

In [13]:
arr.ndim

2

In [14]:
np.expand_dims(arr, axis = 0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr, axis = 1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr, axis = 0).ndim

3

In [17]:
a = np.array ([[1],[2],[3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [19]:
a.ndim

2

In [20]:
np.squeeze(a) #Remove axes of length one from 'a'

array([1, 2, 3])

In [21]:
a

array([[1],
       [2],
       [3]])

In [22]:
np.repeat(a,5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [23]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [24]:
np.repeat(arr1,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2])

In [25]:
np.repeat(arr1, 2, axis=0) #axis wise repeatition.

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 1],
       [1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [26]:
np.repeat(arr1, 3, axis=1) #column wise repeatition.

array([[1, 1, 1, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 1, 1, 1],
       [2, 2, 2, 1, 1, 1, 2, 2, 2]])

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [29]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [30]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [31]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [34]:
np.roll(c,2,axis=1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [36]:
arr2

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [37]:
arr1 + arr2

array([[3, 4, 4],
       [3, 3, 3],
       [4, 2, 4]])

In [38]:
arr1 - arr2

array([[-1,  0,  0],
       [-1,  1, -1],
       [ 0,  0,  0]])

In [39]:
arr1 * arr2

array([[2, 4, 4],
       [2, 2, 2],
       [4, 1, 4]])

In [40]:
arr1 > arr2

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [41]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [42]:
~arr1

array([[-2, -3, -3],
       [-2, -3, -2],
       [-3, -2, -3]])

In [43]:
# Operations on numpy string array

In [44]:
d = np.array(["pw","skills"])

In [45]:
d

array(['pw', 'skills'], dtype='<U6')

In [46]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [47]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [48]:
# mathematical functions

In [49]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [50]:
arr2

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [51]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.90929743],
       [0.84147098, 0.90929743, 0.84147098],
       [0.90929743, 0.84147098, 0.90929743]])

In [52]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [ 0.54030231, -0.41614684,  0.54030231],
       [-0.41614684,  0.54030231, -0.41614684]])

In [53]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -2.18503986],
       [ 1.55740772, -2.18503986,  1.55740772],
       [-2.18503986,  1.55740772, -2.18503986]])

In [54]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103]])

In [55]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [56]:
np.power(arr1, 3)

array([[1, 8, 8],
       [1, 8, 1],
       [8, 1, 8]])

In [57]:
np.mean(arr1)

1.5555555555555556

In [58]:
np.min(arr1)

1

In [59]:
np.max(arr1)

2

In [60]:
np.std(arr1) # Standard deviation

0.4969039949999533

In [61]:
np.var(arr1) # variance

0.2469135802469136

In [62]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  1, -1],
       [ 0,  0,  0]])

In [63]:
np.subtract(arr1,arr2)

array([[-1,  0,  0],
       [-1,  1, -1],
       [ 0,  0,  0]])

In [64]:
np.multiply(arr1,arr2)

array([[2, 4, 4],
       [2, 2, 2],
       [4, 1, 4]])

In [65]:
np.mod(arr1,arr2) #return element wise remainder

array([[1, 0, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [66]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [67]:
#sort search
e = np.array([5,6,1,2])

In [68]:
e

array([5, 6, 1, 2])

In [69]:
np.sort(e)

array([1, 2, 5, 6])

In [70]:
f = np.array([5, 199, 200, 6, 7, 8])
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [71]:
np.searchsorted(f,170) # Find indices where elements should be inserted to maintain order.

6

In [72]:
f = np.array([5, 199, 200, 6, 7,0,0,0, 8])

In [73]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [74]:
np.count_nonzero(f)

6

In [75]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [76]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8]),)

In [77]:
np.extract(f>0,f)

array([  5, 199, 200,   6,   7,   8])

In [78]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [79]:
f.byteswap() #give byte representation

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [80]:
# matrix >>> 2d array

import numpy.matlib as nm

In [81]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [82]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [83]:
# numpy linear algebra

arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [84]:
arr1

array([[1, 9, 7],
       [7, 2, 1],
       [7, 4, 9]])

In [85]:
arr2

array([[1, 5, 5],
       [3, 3, 8],
       [1, 7, 6]])

In [86]:
arr1 @ arr2

array([[ 35,  81, 119],
       [ 14,  48,  57],
       [ 28, 110, 121]])

In [87]:
arr1

array([[1, 9, 7],
       [7, 2, 1],
       [7, 4, 9]])

In [88]:
np.linalg.det(arr1)

-392.0000000000002

In [89]:
np.linalg.inv(arr1)

array([[-0.03571429,  0.13520408,  0.0127551 ],
       [ 0.14285714,  0.10204082, -0.12244898],
       [-0.03571429, -0.1505102 ,  0.15561224]])

In [90]:
# To solve eqns and get the values of x,y,z

In [91]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [92]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [93]:
b = np.array([16,8,0])

In [94]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])